### PR TITLE
Styling

### LINKED ISSUE #8: Article show layout
Basic wireframe structure: 
- Title
- Carousel
- Content
- Comment-section

### LINKED ISSUE #9: Styling
Create basic brand by: 
- colors
- font

### PR DESCRIPTION
**Pull request by Antholimere**
- [x] Removed the DS_STORE files
- [x] Home picture (first section on homepage)
- [x] Home section positioning
- [x] Carousel
- [x] Navbar
- [x] Link homepage button to latest article
- [x] About layout

closes https://github.com/AnaYs/latitudes/issues/9
closes https://github.com/AnaYs/latitudes/issues/8

### CODE REVIEW

**Comment by AnaYs** [comment]
How do we choose fonts and colors? I liked what you showed me yesterday but I thought that it might be pretty close to alexhonnold's version. What about the font of the "OR" - would you think thats nice to use for the Chasing Latitutes title?

**Comment by Antholimere** [comment]
screen shot 2016-09-06 at 15 18 35

**Comment by Antholimere** [comment]
I think it's a good idea to choose the main font and colors, easier to do when more views are made (i.e. article show). I like the title this way, feels playful.

What do you think about the 'Read latest' button? @AnaYs 
Also I plan on linking your name (subtitle) to the about page also. I underlined it to make it more clear, what do you think? It would look like this http://recordit.co/1zRGOsMINp
The down-arrow styling is temporary fa fa icon, I think it'll look better with a thin and subtle arrow afterwards?

**Comment by Antholimere** [comment]
Until further design questions are discussed, this is the about layout
screen shot 2016-09-10 at 15 13 08

**Comment by Antholimere** [comment]
screen shot 2016-09-12 at 13 36 25

**Comment by Antholimere** [comment]
Instagram feed is to be added under the profile picture:

**Pull request merged**
